### ISSUE TITLE
Wrong size in Manage Backups

### ISSUE THREAD

**Issue by twister65** [twister65/com_akeeba-core#1]
After restoring a split backup, the size is not correct in the "Manage Backups" view.
![ManageBackups](https://user-images.githubusercontent.com/26852967/58371999-58111280-7f17-11e9-8b09-dd27cbc65d0d.png)

The `multipart` and `total_size` columns in the `#__ak_stats` table are equal to 0.

In configuration, "Part size for split archives" is set to 1 MB.

**Comment by twister65** [comment]
@nikosdion , is this an issue with the `update_statistics` function ?
https://github.com/twister65/com_akeeba-core/blob/1948408a6fb6779ee3f4fa2c80ba0e69e5fa81b0/backend/BackupEngine/Core/Domain/Finalization.php#L680
We can also reproduce this issue with MySQL.

**Comment by nikosdion** [comment]
I do not provide free of charge support. I have a family to feed and bills to pay.
